ABTests Api
RbxAPI/Pyblox pull request #13
Opened 2020-12-10 20:57 UTC by mfd-co

DO NOT EXPECT THIS TO LOOK NICE AT ALL.
In consideration that Python is not my main language, this will look weird to some.

2020-12-11 16:13 UTC, Sanjay-B requested changes
Solid stuff. Left a review. Please correct & read the stuff posted. Thanks for the contributions.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +# Info for sanjay, v1/enrollments is v1/get-enrollments, but the only difference is, is that SubjectType is a string
Remove this. Got it.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +# FIXME The awful code below.
Keep this. This comment is fine.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +# TODO Make this less verbose and use kwargs
Please use ``kwargs`` so that it follows the same design as the rest of the library.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +    """
Skeptical about leaving documentation in here. Perhaps, we document (in a basic readme), the endpoints that do not have documentation. What do you think? The library is designed to follow the root's docs but, perhaps a special case can be made for roots that do not have docs.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +    if len(ExperimentName) > 50:
Can be combined with line 33 & returned a range between 0-50.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +def createGetEnrollmentType(ExperimentName: str, SubjectType: str or int, SubjectTargetId: int) -> dict:
It's a bit weird/uncanny that this is outside the class. Idk how I feel about that. Consider moving inside class.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +    # POST https://abtesting.roblox.com/v1/get-enrollments
The ``#Docs`` comment should point to where documentation is; a readme file or a doc url.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +        """
Perhaps, we should move this to a readme. I don't want the file to get cluttered over comments. Rather keep those minimal. I'm looking for solutions to correct this.

2020-12-11 16:13 UTC, Sanjay-B commented on pyblox3/src/abtesting.py
> +            raise RuntimeError("You are unauthorised to create this request with the credentials you supplied!")
Error codes are handled automatically by the library. You could just return ``return False, response[4]``. POST, PATCH, DEL are treated as tuples to allow for comparison and an easy what to "prove" confirmation that the action completed (true) or not (false).

2020-12-11 16:13 UTC, Sanjay-B commented on examples/ABTests.py
> +#
Example is actually pretty good. I'm going to write an actual bot interface once the library reaches 80% API completion across all roots. For now, just make sure that the endpoints actually work & can be used with or without a bot interface (compatibility w/ Discord.py, etc).

2020-12-11 17:02 UTC, mfd-co commented on pyblox3/src/abtesting.py
> +        return {'ExperimentName': ExperimentName, 'SubjectType': SubjectType, 'SubjectTargetId': SubjectTargetId}
```suggestion
    @staticmethod
    def createGetEnrollmentType(**kwargs):
        ExperimentName = kwargs.get("ExperimentName", None)
        SubjectType = kwargs.get("SubjectType", None)
        SubjectTargetId = kwargs.get("SubjectTargetId", None)
        if len(ExperimentName) == 0 or len(ExperimentName) > 50:
            raise SyntaxError("The ExperimentName should not be empty or greater than 50 characters.")
        if SubjectTargetId < 1:
            raise SyntaxError("In order to satisfy the request, the SubjectTargetId is required to be greater than 0.")
        if (type(SubjectType) == int and SubjectType > 2) \
                or (type(SubjectType) == int and SubjectType < 1) \
                or (type(SubjectType) == str and len(SubjectType) == 0):
            raise SyntaxError("In order to satisfy the request, the SubjectType is required to 1 or 2 "
                              "or User or BrowserTracker")
        return {'ExperimentName': ExperimentName, 'SubjectType': SubjectType, 'SubjectTargetId': SubjectTargetId}
```

2020-12-11 20:06 UTC, Pythonic-Rainbow commented on pyblox3/src/abtesting.py
> +        return {'ExperimentName': ExperimentName, 'SubjectType': SubjectType, 'SubjectTargetId': SubjectTargetId}
ok

2020-12-11 20:10 UTC, mfd-co commented on pyblox3/src/abtesting.py
> +        return {'ExperimentName': ExperimentName, 'SubjectType': SubjectType, 'SubjectTargetId': SubjectTargetId}
ok also

2020-12-19 04:01 UTC, Sanjay-B approved these changes
Looks good on my end. Shouldn't break anything on this branch.

2020-12-19 04:02 UTC, merged